name: build (macOS)

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install open-mpi hdf5 eigen@3.4 openblas

      - name: Build
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_PREFIX_PATH="$(brew --prefix)" ..
          make -j4

      - name: Test
        env:
          HDF5_USE_FILE_LOCKING: 'FALSE'
          OMP_NUM_THREADS: 1
        run: |
          cd build
          ctest -j1
